#pragma once

#include "types.h"

static const set<string> IMPLEMENTED_BENCHMARKS = {
    "TEST", "TEST1", "TEST2", "TEST3", "TEST4", "TEST5", "TEST6",
    

    "BW_ALL_HIT_BASE_SINGLE", "BW_ALL_HIT_BASE_PERCORE", "BW_ALL_HIT_PT_SINGLE", "BW_ALL_HIT_PT_PERCORE", "BW_ALL_HIT_PC_SINGLE", "BW_ALL_HIT_PC_PERCORE",
    "BW_ALL_MISS_BASE_SINGLE", "BW_ALL_MISS_BASE_PERCORE", "BW_ALL_MISS_PT_SINGLE", "BW_ALL_MISS_PT_PERCORE", "BW_ALL_MISS_PC_SINGLE", "BW_ALL_MISS_PC_PERCORE",
    "BW_ALL_RAND_BASE_SINGLE", "BW_ALL_RAND_BASE_PERCORE", "BW_ALL_RAND_PT_SINGLE", "BW_ALL_RAND_PT_PERCORE", "BW_ALL_RAND_PC_SINGLE", "BW_ALL_RAND_PC_PERCORE",
    
    "BW_ALL_SC0_HIT_PT_SINGLE", "BW_ALL_SC0_HIT_PT_PERCORE", "BW_ALL_SC0_MISS_PT_SINGLE", "BW_ALL_SC0_MISS_PT_PERCORE", "BW_ALL_SC0_RAND_PC_SINGLE",
    "BW_ALL_SC1_HIT_PT_SINGLE", "BW_ALL_SC1_HIT_PT_PERCORE", "BW_ALL_SC1_MISS_PT_SINGLE", "BW_ALL_SC1_MISS_PT_PERCORE", "BW_ALL_SC1_RAND_PC_SINGLE",
    
    "BW_ALL_BA2_HIT_PT_SINGLE", "BW_ALL_BA2_HIT_PT_PERCORE", "BW_ALL_BA2_MISS_PT_SINGLE", "BW_ALL_BA2_MISS_PT_PERCORE", "BW_ALL_BA2_RAND_PC_SINGLE",
    "BW_ALL_BA3_HIT_PT_SINGLE", "BW_ALL_BA3_HIT_PT_PERCORE", "BW_ALL_BA3_MISS_PT_SINGLE", "BW_ALL_BA3_MISS_PT_PERCORE", "BW_ALL_BA3_RAND_PC_SINGLE",
    "BW_ALL_BA1_HIT_PT_SINGLE", "BW_ALL_BA1_HIT_PT_PERCORE", "BW_ALL_BA1_MISS_PT_SINGLE", "BW_ALL_BA1_MISS_PT_PERCORE", "BW_ALL_BA1_RAND_PC_SINGLE",
    "BW_ALL_BG4_BA1_HIT_PT_SINGLE", "BW_ALL_BG4_BA1_HIT_PT_PERCORE", "BW_ALL_BG4_BA1_MISS_PT_SINGLE", "BW_ALL_BG4_BA1_MISS_PT_PERCORE", "BW_ALL_BG4_BA1_RAND_PC_SINGLE",
    "BW_ALL_BG4_HIT_PT_SINGLE", "BW_ALL_BG4_HIT_PT_PERCORE", "BW_ALL_BG4_MISS_PT_SINGLE", "BW_ALL_BG4_MISS_PT_PERCORE", "BW_ALL_BG4_RAND_PC_SINGLE",

    "BW_R0_HIT_BASE_SINGLE", "BW_R0_HIT_BASE_PERCORE", "BW_R0_HIT_PT_SINGLE", "BW_R0_HIT_PT_PERCORE", "BW_R0_HIT_PC_SINGLE", "BW_R0_HIT_PC_PERCORE",
    "BW_R0_MISS_BASE_SINGLE", "BW_R0_MISS_BASE_PERCORE", "BW_R0_MISS_PT_SINGLE", "BW_R0_MISS_PT_PERCORE", "BW_R0_MISS_PC_SINGLE", "BW_R0_MISS_PC_PERCORE",
    "BW_R0_RAND_BASE_SINGLE", "BW_R0_RAND_BASE_PERCORE", "BW_R0_RAND_PT_SINGLE", "BW_R0_RAND_PT_PERCORE", "BW_R0_RAND_PC_SINGLE", "BW_R0_RAND_PC_PERCORE",

    "BW_R0_SC0_HIT_PT_SINGLE", "BW_R0_SC0_HIT_PT_PERCORE", "BW_R0_SC0_MISS_PT_SINGLE", "BW_R0_SC0_MISS_PT_PERCORE", "BW_R0_SC0_RAND_PC_SINGLE",
    "BW_R0_SC1_HIT_PT_SINGLE", "BW_R0_SC1_HIT_PT_PERCORE", "BW_R0_SC1_MISS_PT_SINGLE", "BW_R0_SC1_MISS_PT_PERCORE", "BW_R0_SC1_RAND_PC_SINGLE",
    
    "BW_R0_BA2_HIT_PT_SINGLE", "BW_R0_BA2_HIT_PT_PERCORE", "BW_R0_BA2_MISS_PT_SINGLE", "BW_R0_BA2_MISS_PT_PERCORE", "BW_R0_BA2_RAND_PC_SINGLE",
    "BW_R0_BA3_HIT_PT_SINGLE", "BW_R0_BA3_HIT_PT_PERCORE", "BW_R0_BA3_MISS_PT_SINGLE", "BW_R0_BA3_MISS_PT_PERCORE", "BW_R0_BA3_RAND_PC_SINGLE",
    "BW_R0_BA1_HIT_PT_SINGLE", "BW_R0_BA1_HIT_PT_PERCORE", "BW_R0_BA1_MISS_PT_SINGLE", "BW_R0_BA1_MISS_PT_PERCORE", "BW_R0_BA1_RAND_PC_SINGLE",
    "BW_R0_BG4_BA1_HIT_PT_SINGLE", "BW_R0_BG4_BA1_HIT_PT_PERCORE", "BW_R0_BG4_BA1_MISS_PT_SINGLE", "BW_R0_BG4_BA1_MISS_PT_PERCORE", "BW_R0_BG4_BA1_RAND_PC_SINGLE",
    "BW_R0_BG4_HIT_PT_SINGLE", "BW_R0_BG4_HIT_PT_PERCORE", "BW_R0_BG4_MISS_PT_SINGLE", "BW_R0_BG4_MISS_PT_PERCORE", "BW_R0_BG4_RAND_PC_SINGLE",


    "BW_R1_HIT_PT_SINGLE", "BW_R1_HIT_PT_PERCORE", "BW_R1_MISS_PT_SINGLE", "BW_R1_MISS_PT_PERCORE", "BW_R1_RAND_PC_SINGLE",

};

inline int randInt(int n) {
    std::uniform_int_distribution<int> dist(0, n - 1);
    return dist(g_gen);
}
inline size_t randSize(size_t n) {
    std::uniform_int_distribution<size_t> dist(0, n - 1);
    return dist(g_gen);
}

// Parsing
vector<uint64_t> parseHexList(const string& input);
vector<string> parseBenchList(const string& input);

void print_help(const char* prog_name);
void print_result(BenchResult res);

// Physical address
uint64_t getPhysicalAddr(void* vaddr);

// DRAM address decoding
int applyXorFunctions(uint64_t physAddr, const vector<uint64_t>& masks);
BankInfo getBankFromPhysicalAddr(uint64_t physAddr);

// Bit utilities
int calcNum(const vector<uint64_t>& masks);
int countSetBits(uint64_t n);
int getMaxBit();
int getMaxOnlyFuncBit();


vector<int> get_thread_list();

uint32_t next_pow2(uint32_t x);
uint32_t ceil_pow2(uint32_t x);

vector<int> make_indices(int n, int total);